export const PATTERNS = [
  {
    id: "binary-search",
    title: "Binary Search",
    description: "Search in a sorted array efficiently.",
  },
  {
    id: "bs-rotated-array",
    title: "Search in Rotated Array",
    description: "Binary search on a rotated sorted array.",
  },
  {
    id: "bs-peak-element",
    title: "Find Peak Element",
    description: "Search for a peak in an array.",
  },
  {
    id: "bs-matrix-search",
    title: "Search in 2D Matrix",
    description: "Binary search mapped to a 2D grid.",
  },
  {
    id: "bs-on-answer",
    title: "BS on Answer (Min/Max)",
    description: "Binary search on the condition space.",
  },
  {
    id: "sliding-window",
    title: "Sliding Window",
    description: "Find max sum subarray of size K.",
  },
  {
    id: "two-pointers",
    title: "Two Pointers",
    description: "Find target sum using dual pointers.",
  },
  {
    id: "fast-slow-pointers",
    title: "Fast & Slow Pointers",
    description: "Cycle detection using Tortoise and Hare.",
  },
  {
    id: "merge-intervals",
    title: "Merge Intervals",
    description: "Handle overlapping intervals efficiently.",
  },
  {
    id: "cyclic-sort",
    title: "Cyclic Sort",
    description: "Sort arrays with numbers in a given range.",
  },
  {
    id: "linked-list-reversal",
    title: "LinkedList Reversal",
    description: "In-place reversal of a linked list.",
  },
  {
    id: "tree-bfs",
    title: "Tree BFS",
    description: "Level order traversal of a tree.",
  },
  {
    id: "tree-dfs",
    title: "Tree DFS",
    description: "Pre-order, In-order, and Post-order traversal.",
  },
  {
    id: "heaps",
    title: "Two Heaps / Top K",
    description: "Find median or top K elements using heaps.",
  },
  {
    id: "subsets",
    title: "Subsets (Combinations)",
    description: "Generate all subsets or permutations.",
  },
  {
    id: "topological-sort",
    title: "Topological Sort",
    description: "Linear ordering of vertices in a DAG.",
  },
  {
    id: "backtracking",
    title: "Backtracking",
    description: "Explore all possible solutions (e.g. N-Queens).",
  },
  {
    id: "trie",
    title: "Trie (Prefix Tree)",
    description: "Efficiently store and search strings.",
  },
  { id: "arr-largest", title: "Largest Element", description: "Find the maximum element in an array." },
  { id: "arr-second-largest", title: "Second Largest", description: "Find the second maximum element." },
  { id: "arr-check-sorted", title: "Check if Sorted", description: "Check if an array is sorted in ascending order." },
  { id: "arr-remove-duplicates", title: "Remove Duplicates", description: "Remove duplicates from a sorted array." },
  { id: "arr-rotate-one", title: "Rotate Array by One", description: "Left rotate the array by one position." },
  { id: "arr-rotate-d", title: "Rotate Array by D", description: "Left rotate the array by D positions." },
  { id: "arr-move-zeros", title: "Move Zeros", description: "Move all zeros to the end of the array." },
  { id: "arr-linear-search", title: "Linear Search", description: "Find an element by checking each index." },
  { id: "arr-union", title: "Union of Arrays", description: "Find the union of two sorted arrays." },
  { id: "arr-missing", title: "Missing Number", description: "Find the missing number in range [1, N]." },
  { id: "arr-max-ones", title: "Max Consecutive Ones", description: "Max count of consecutive 1s in a binary array." },
  { id: "arr-single-number", title: "Single Number", description: "Find the element that appears only once." },
  { id: "arr-longest-subarray-k", title: "Longest Subarray Sum K", description: "Find max length subarray with sum K." },
  { id: "arr-two-sum", title: "Two Sum", description: "Find indices of two numbers that sum to target." },
  { id: "arr-sort-colors", title: "Sort Colors (0s, 1s, 2s)", description: "Sort an array of 0s, 1s, and 2s." },
  { id: "arr-majority-element", title: "Majority Element", description: "Find element that appears > n/2 times." },
  { id: "arr-kadanes", title: "Kadane's Algorithm", description: "Find max sum subarray." },
  { id: "arr-stocks", title: "Buy & Sell Stocks", description: "Max profit from single transaction." },
  { id: "arr-rearrange-sign", title: "Rearrange by Sign", description: "Rearrange array elements as [+ , - , + , -]." },
  { id: "arr-next-permutation", title: "Next Permutation", description: "Find the lexicographically next greater permutation." },
  { id: "arr-leaders", title: "Leaders in Array", description: "Find elements greater than all elements to their right." },
  { id: "arr-longest-consecutive", title: "Longest Consecutive Sequence", description: "Find longest sequence of consecutive integers." },
  { id: "arr-set-matrix-zero", title: "Set Matrix Zeroes", description: "Set rows and columns to zero if element is 0." },
  { id: "arr-rotate-image", title: "Rotate Image", description: "Rotate a square matrix by 90 degrees." },
  { id: "arr-spiral-matrix", title: "Spiral Matrix", description: "Print matrix elements in spiral order." },
  { id: "arr-pascals-triangle", title: "Pascal's Triangle", description: "Generate Pascal's triangle rows." },
];
